### ISSUE TITLE
hosting the project with a web UI

### ISSUE THREAD

**Issue by ayuhsya** [metakgp/mftp#12]
Is it possible to host this project, so that people may actually use it?
I was thinking of creating a web UI where people can subscribe to get emails from CDC Notice Board. This will be different from the already existing CDC Notify app in that the attachments in the notice will be attached to the email.
I would like to know if this is a feasible goal.

**Comment by vivekiitkgp** [comment]
I think we should discuss this (in more details) in one of the metakgp's meetings. However, in short, we have thought of this idea before and did not implement it for several reasons. One of them being the sensitivity of released information and potential issues it could create with CDC.

Feel free to discuss more when we meet.
