### ISSUE TITLE
When secret_answer entered by user is wrong, it should throw a better error

### ISSUE THREAD

**Issue by icyflame** [metakgp/mftp#13]
The `r.history` array becomes empty and thus [this line](https://github.com/metakgp/mftp/blob/575a35718e3c96515ce182094aaec327c3fdf3fd/erp.py#L71) throws this error:

```sh
Traceback (most recent call last):
  File "update.py", line 132, in <module>
    check_notices()
  File "path/erp.py", line 77, in wrapped_func
    r.history[1].headers['Location']).group(1)
IndexError: list index out of range
```

Instead, if before accessing `r.history[1]`, it should ensure that `r.history`'s size is at least 2 and if the size is less than 2, it should ask the user to check their secret answer settings (probably a typo in one of the answers)

**Comment by piyush27ranjan** [comment]
I would like to take up this issue

**Comment by icyflame** [comment]
@piyush27ranjan Sure! Let me know here or on Slack if you have face any trouble. This should be fairly easy to implement and test. :slightly_smiling_face:

**Comment by thealphadollar** [comment]
@icyflame What exactly do we aim to accomplish here?

**Comment by icyflame** [comment]
It's a very simple fix: throw a meaningful error instead of `IndexError`. i.e try-catch, show the appropriate error.
