### ISSUE TITLE
Change subject from "Notice: CV submission" to "Placement: CV submission" 

### ISSUE THREAD

**Issue by kaustubhhiware** [metakgp/mftp#24]
It would be better if the subject is changed from `Notice: CV Submission - Company` to `Internship: CV Submission - Company` or `Placement: Urgent - CV Verification`.

This is possible since the first line mentions type:placement or type:internship. This would help reduce confusions amongst people sitting for placements who might confuse notices of internship as being of placements.

**Comment by thealphadollar** [comment]
This is stale; I do not think that this is required. This will lead us to depend more on how the CDC publishes notices which may change frequently. Please give me your views; I shall close the issue.
