### ISSUE TITLE
Understand why bs4 recursion depth exceeded happens

### ISSUE THREAD

**Issue by amrav** [metakgp/mftp#28]
Something about the notice format changed

**Comment by thealphadollar** [comment]
We observed that our previous recursion limit is failing against the current (more shitier) formatting of the CDC notices. This was done in PR #27 .

The concerned code segment is https://github.com/metakgp/mftp/blob/3e5c1a40cfca8216ad94c10481cc726fe930ff12/update.py#L58

The fix applied is not permanent and a better method is to be looked after.

**Comment by thealphadollar** [comment]
We haven't faced the same problem for more than an year now, I believe we may want to close the issue.
