### ISSUE TITLE
Add a sanity check (that can't go wrong normally) to make sure that the system is working atleast

### ISSUE THREAD

**Issue by icyflame** [metakgp/mftp#4]
- If the sanity check goes wrong, then send an email out to everyone informing them that the system _may_ not be working right.
- discussed this with @amrav

**Comment by amrav** [comment]
The point of a sanity check in this case is not that it can't go wrong normally, but that if something goes wrong, it must definitely fire. False positives are tolerable, false negatives are not.

**Comment by thealphadollar** [comment]
@amrav @icyflame Do you think we can add some more details to the issue? I feel it is very vague at the moment, and that is understandable as you'd have created it for our use. However, now we have a lot of new contributors and the description is not helping them - restraining them from contributions :disappointed:

**Comment by proffapt** [comment]
This is a part of the revamp plan in https://github.com/metakgp/mftp/issues/55. Closing it, will create an elaborated issue for subtask as the work progresses..
