### ISSUE TITLE
[IMPROVEMENT] Failure Monitoring

### ISSUE THREAD

**Issue by thealphadollar** [metakgp/mftp#40]
## Context

If and when #38 is implemented using Heroku Scheduler, we will need a better way to get notified when the service is not working. Here are key things to note:

1. When we are running on the Heroku scheduler, there is a "very rare" chance of the job not running or getting missed.
2. The above is taken care of by Heroku itself, and we do not have to worry about the same. So, the fault we should be notified of is when the script runs but fails.

## Requirement

A localized (can pinpoint the exact place that threw the error) and minimal (so that the maintainers do not mark it as spam and multiple maintainers can be added). A good way would be to use the existing mailing mechanism setup using Mailgun REST API. We should also aim at keeping the configuration and reconfiguration overhead as low as possible, if feasible, we should pass it from Github itself.

NOTE: **this should ideally be done after #38** 

## Resources

- For python exception handling: https://www.programiz.com/python-programming/exception-handling

**Comment by thealphadollar** [comment]
cc/ @iakshat @icyflame What ideas do you have regarding the above?

**Comment by nilesh05apr** [comment]
@thealphadollar is there a way to monitor failure for github actions?

**Comment by thealphadollar** [comment]
Yes. As we implement it, it'll show us in the actions tab if it fails or succeeds.
