### ISSUE TITLE
Move from Python 2 to 3

### ISSUE THREAD

**Issue by chirag-ghosh** [metakgp/mftp#47]
Heroku-18 (currently used and the only version to support python 2) has reached its [End-of-Life](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq). 
For newer builds to take place we need to upgrade to Heroku-22. So a migration of code to the latest version of Python is necessary.

**Comment by Teerath-Agarwal** [comment]
I'll be working on it. Will provide an update about the progress 12 hours from now.

**Comment by 1rsh** [comment]
I have a sample code ready that utilises selenium in python and sends out the mail. Not really sure about the deployment process though.

**Comment by chirag-ghosh** [comment]
@1rsh what will be the benefits of moving to selenium? I am not that experienced in python but I feel upgrading the current codebase to python3 would be faster. 
If you want to deploy and run your version of code, you can utilise the [Github student developer pack](https://education.github.com/pack) and/or AWS free tier to set it up

**Comment by 1rsh** [comment]
@chirag-ghosh The main reason I prefer selenium is that if erp decides to revamp its notice board page then it will be easier to migrate + if we wish to add additional functions then I find selenium to extend. The only drawback I feel is that it is a tad bit slower but since we are already checking the site in regular intervals of time, it won't affect the end result much.

**Comment by chirag-ghosh** [comment]
That can be done but we should put it as a target in the long run. Currently making the project up and running again should be our priority I feel.

**Comment by 1rsh** [comment]
> That can be done but we should put it as a target in the long run. Currently making the project up and running again should be our priority I feel.

I have completed the code for this. It is up and running. I wasn't sure how to deploy it for free. I'll share the code maybe on this thread or through some other medium by tonight.

**Comment by chirag-ghosh** [comment]
You can deploy it for free using AWS free tier or Github student developer pack

**Comment by harshkhandeparkar** [comment]
> > That can be done but we should put it as a target in the long run. Currently making the project up and running again should be our priority I feel.
> 
> I have completed the code for this. It is up and running. I wasn't sure how to deploy it for free. I'll share the code maybe on this thread or through some other medium by tonight.

You can open a separate PR and issue for this discussion. Until we finalize it, we can use the current code (with Python3).

**Comment by Teerath-Agarwal** [comment]
update: Most of the code is migrated. Some bugs have been encountered in the process, trying to debug.

**Comment by chirag-ghosh** [comment]
cool @Teerath-Agarwal. Feel free to create a PR whenever you are ready.
