### ISSUE TITLE
MFTP doctor

### ISSUE THREAD

**Issue by proffapt** [metakgp/mftp#60]
Get notified of any abnormality, basically a sanity check. Will add and remove a cronjob which keeps checking on the status of mftp and logs and reports when it detects any abnormality.

- [x] Implement `mftp-doctor` script
- [x] Dockerise it
- [x] Incorporate into script
   - `mftp doctor enable`
   - `mftp doctor enable 10`
   - `mftp doctor disable`

> [!Note]
> Use [ntfy](https://github.com/binwiederhier/ntfy) for sending notifications of doctor.

**Comment by mitaliruhela** [comment]
hey, can you assign me this.

**Comment by proffapt** [comment]
Cools!

**Comment by mitaliruhela** [comment]
I try my best to solve the issue. Thanks for assigning.
