### ISSUE TITLE
Logs rotation

### ISSUE THREAD

**Issue by proffapt** [metakgp/mftp#63]
Implement logs rotation to save disk storage :)
Refer: https://en.wikipedia.org/wiki/Log_rotation

**Comment by yash8000** [comment]
hey,, can you assign me this

**Comment by proffapt** [comment]
great! best of luck.

**Comment by yash8000** [comment]
Got it, thanks!

**Comment by mitaliruhela** [comment]
Hey, can you assign this issue to me.

**Comment by proffapt** [comment]
@yash8000 are you working on it?

**Comment by yash8000** [comment]
i am having issue with permission denied access regarding running the bash
script , that.s the only issue i am facing

**Comment by proffapt** [comment]
try 
```sh
chmod +x <script.sh>
```
