### ISSUE TITLE
NTFY Support

### ISSUE THREAD

**Issue by proffapt** [metakgp/mftp#79]
Google groups suck (see [this](https://github.com/metakgp/mftp/issues/71)). PWA is too much work (see [this](https://github.com/metakgp/mftp/issues/75)).

There are broadly two steps:
- [x] #81
- [x] #82

**Comment by BAGUVIX456** [comment]
Can I work on this?

**Comment by proffapt** [comment]
Great! Assigning you with this. Will brief you about a few things over a meet.
